# Set to true to add reviewers to pull requests (required)
# addReviewers: true

# Set to true to add assignees to pull requests
# addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user name) (required)
# reviewers: []

# A number of reviewers added to the pull request (required)
# Set 0 to add all the reviewers (default: 0)
# numberOfReviewers: 0
# A list of assignees, overrides reviewers if set
# assignees: []
# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
# numberOfAssignees: 2

# Set to true to add reviewers from different groups to pull requests
# useReviewGroups: true

# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
# reviewGroups:
#   groupA:
#     - reviewerA
#     - reviewerB
#     - reviewerC
#   groupB:
#     - reviewerD
#     - reviewerE
#     - reviewerF

# Set to true to add assignees from different groups to pull requests
# useAssigneeGroups: false

# A list of assignees, split into different froups, to be added to pull requests (GitHub user name)
# assigneeGroups:
#   groupA:
#     - assigneeA
#     - assigneeB
#     - assigneeC
#   groupB:
#     - assigneeD
#     - assigneeE
#     - assigneeF

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - WIP
  - wip
# A list of users to be skipped by both the add reviewers and add assignees processes
# skipUsers:
#   - dependabot[bot]
